### ISSUE TITLE
Vega configuration files do not accept system variables

### ISSUE THREAD

**Issue by iprafols** [andreicuceu/vega#71]
In the Vega config files I used environmental variables (as I used to do in fitter2), and I get the following error:
```
Traceback (most recent call last):
  File "/global/homes/i/iprafols/desi/git/vega/bin/run_vega_mpi.py", line 14, in <module>
    vega = VegaInterface(args.config)
  File "/global/homes/i/iprafols/.local/lib/python3.8/site-packages/vega/vega_interface.py", line 66, in __init__
    self.data[name] = data.Data(corr_item)
  File "/global/homes/i/iprafols/.local/lib/python3.8/site-packages/vega/data.py", line 36, in __init__
    rp_rt_grid, z_grid = self._read_data(data_path,
  File "/global/homes/i/iprafols/.local/lib/python3.8/site-packages/vega/data.py", line 133, in _read_data
    hdul = fits.open(find_file(data_path))
  File "/global/homes/i/iprafols/.local/lib/python3.8/site-packages/vega/utils.py", line 420, in find_file
    raise RuntimeError('The path/file does not exists: ', input_path)
RuntimeError: ('The path/file does not exists: ', PosixPath('$REDO_DR16/Correlation/cf_z_0_10-exp.fits'))
```

I think this is something useful to have

**Comment by andreicuceu** [comment]
Hi @iprafols, I just added a small change that does os.path.expandvars() on paths before checking them. Hopefully this solves the problem. Please try again with the updated version and let me know if it works now.
You can also have a look at the find_file() function (lines 382-420 of https://github.com/andreicuceu/vega/blob/master/vega/utils.py). That's the function I use to check the paths. Let me know if I missed something else as well.

**Comment by iprafols** [comment]
That was quick, it seems to work now. Thanks
